dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    implementation "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"
    implementation(include("com.github.pemistahl:lingua:1.2.2"))
    compileOnly("com.terraformersmc:modmenu:${rootProject.modmenu_version}") {
        exclude group: 'net.fabricmc.fabric-api'
    }

    implementation(project(':common')) { transitive = false }
}

loom {
    mods {
        chatglot {
            sourceSet project(':common').sourceSets.main
            sourceSet sourceSets.main
        }
    }
}

jar {
    from(project(':common').sourceSets.main.output)
}

sourcesJar {
    from(project(':common').sourceSets.main.allSource)
}
