org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.warning.mode=all

minecraft_version=26.2

enabled_platforms=fabric

mod_id=chatglot
archives_base_name=chatglot
mod_version=0.1.0
maven_group=io.github.chatglot
java_version=25

fabric_loader_version=0.19.3
fabric_api_version=0.152.1+26.2
fabric_loader_version_range=>=0.19.3
fabric_api_version_range=>=0.150.1+26.2

moddeck_version=0.1.0
modmenu_version=20.0.0-beta.3

supported_minecraft_version_range=26.2.x
